### ISSUE TITLE
Error in set up VQGAN

### ISSUE THREAD

**Issue by HindAB1** [borisdayma/dalle-mini#102] opened 2021-11-07 06:49 UTC
I tried to run the model and in set up VQGAN it shows the below error. 

ValueError                                Traceback (most recent call last)
<ipython-input-13-00923b8dba5a> in <module>()
      1 # set up VQGAN
----> 2 vqgan = VQModel.from_pretrained(VQGAN_REPO, revision=VQGAN_COMMIT_ID)

/usr/local/lib/python3.7/dist-packages/transformers/modeling_flax_utils.py in from_pretrained(cls, pretrained_model_name_or_path, dtype, *model_args, **kwargs)
    402                 else:
    403                     raise ValueError(
--> 404                         f"Trying to load the pretrained weight for {key} failed: checkpoint has shape "
    405                         f"{state[key].shape} which is incompatible with the model shape {random_state[key].shape}. "
    406                         "Using `ignore_mismatched_sizes=True` if you really want to load this checkpoint inside this "

ValueError: Trying to load the pretrained weight for ('decoder', 'mid', 'attn_1', 'norm', 'bias') failed: checkpoint has shape (1, 1, 1, 512) which is incompatible with the model shape (512,). Using `ignore_mismatched_sizes=True` if you really want to load this checkpoint inside this model.

**please let mw know how can i fix it? 
Thanks in advance.**

**Comment by borisdayma** [comment] 2021-11-08 15:11
Duplicate of #99

**Closed by borisdayma** 2021-11-08 15:11 UTC
